In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")  #注意这里不是指所有的向量放在GPU上，而是指这个向量的计算在GPU上进行
x = torch.ones(5,3)
x = x.to(device)
x = x.to(torch.int32)
print(x.numel())
print(x.shape)
print(x.ndim)
print(x.device)
print(x)
y = torch.rand(5,3)
y.device     #这里输出的就是cpu

15
torch.Size([5, 3])
2
cuda:0
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], device='cuda:0', dtype=torch.int32)


device(type='cpu')

In [ ]:
#参与运算的 Tensor 必须在同一个 device 上
a = torch.randn(3, 3)
b = torch.randn(3, 3)
b = b.to(device)

c = a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [9]:
a = torch.randn(3, 3).cuda()
b = torch.randn(3, 3)
b = b.to(device)

c = a + b
c


tensor([[-0.8216,  0.6173, -0.7698],
        [-1.3196, -1.5638, -3.0383],
        [-1.2544,  0.0588, -2.2652]], device='cuda:0')

In [18]:
d = torch.arange(10)
print(d)
d = d.reshape(2, 5)
print(d)
d.shape

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


torch.Size([2, 5])

In [ ]:
#reshape 里的 -1

e = torch.arange(24)
e = e.reshape(3, -1, 4)   # -1 意思是自动计算出这一维的大小，保证总元素数量不变
e 

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
f = torch.tensor([
    [1, 2],
    [3, 4]
])

g = torch.tensor([
    [5, 6],
    [7, 8]
])
torch.cat([f, g], dim=0)  # 按行拼接
torch.cat([f, g], dim=1)  # 按列拼接

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

# 除了被拼接的维度之外，其他维度必须一致。
A = [2, 3, 4]   # 这里说的是向量的维度
B = [2, 5, 4]    
torch.cat([A, B], dim=1)

结果维度：[2, 8, 4]


torch.cat([A, B], dim=0)

这个不能拼接  因为 3 != 5


# cat 和 stack 一定要分清

给你一个记忆方法：

cat
不增加维度
stack
增加一个维度

例如：

A.shape = [3, 4]
B.shape = [3, 4]

执行：

torch.cat([A, B], dim=0)

结果：

[6, 4]

执行：

torch.stack([A, B], dim=0)

结果：

[2, 3, 4]

In [4]:
import torch
a = torch.rand(3, 4)
b = torch.rand(3, 4)
c = a + b
c

tensor([[0.9362, 0.5902, 1.7128, 1.4849],
        [1.1161, 0.9557, 0.5567, 1.0774],
        [1.8890, 0.5072, 0.5236, 1.0723]])

In [9]:
A = torch.tensor([
    [1., 2.],
    [3., 4.]
])

B = torch.tensor([
    [5., 6.],
    [7., 8.]
])
print(A * B)
A@B

A=A.permute(1, 0)
A


tensor([[ 5., 12.],
        [21., 32.]])


tensor([[1., 3.],
        [2., 4.]])

# keepdim 是 PyTorch 中一个非常实用的参数，用于控制是否保持原有维度。

In [10]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # shape: (2, 3)

# keepdim=False（默认）
sum1 = x.sum(dim=0, keepdim=False)
print(sum1)        # tensor([5, 7, 9])
print(sum1.shape)  # torch.Size([3])  维度从2维变成1维

# keepdim=True
sum2 = x.sum(dim=0, keepdim=True)
print(sum2)        # tensor([[5, 7, 9]])
print(sum2.shape)  # torch.Size([1, 3])  维度保持2维，第0维变成1

tensor([5, 7, 9])
torch.Size([3])
tensor([[5, 7, 9]])
torch.Size([1, 3])


In [10]:
#统计运算
import torch

x = torch.tensor([
    [1., 2., 3.],
    [4., 5., 6.]
])

print(x.mean())  # 计算所有元素的平均值
print(x.mean(dim=0))  # 按列计算平均值
print(x.mean(dim=1))  # 按行计算平均值
print(x.sum())  # 计算所有元素的和
print(x.sum(dim=0))  # 按列计算和
print(x.sum(dim=1))  # 按行计算和
print(x.max())  # 计算所有元素的最大值
print(x.max(dim=0))  # 按列计算最大值
print(x.min(dim=1))  # 按行计算最小值
print(x.std())  # 计算所有元素的标准差
print(x.std(dim=0))  # 按列计算标准差
print(x.var())  # 计算所有元素的方差
print(x.var(dim=0))  # 按列计算方差

tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor(6.)
torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
torch.return_types.min(
values=tensor([1., 4.]),
indices=tensor([0, 0]))
tensor(1.8708)
tensor([2.1213, 2.1213, 2.1213])
tensor(3.5000)
tensor([4.5000, 4.5000, 4.5000])


# PyTorch 广播机制（Broadcasting）

## 一、广播的核心规则：PyTorch 是如何判断的？

当两个 Tensor 参与运算（如加法、减法、乘法、除法等）时，PyTorch 会**从后往前**（即从最后一维开始）逐个维度对比它们的形状。

只要对应的两个维度满足以下 **两个条件之一**，这两个维度就被认为是**兼容**的：

1. **两个维度的长度相等**
2. **其中一个维度的长度为 `1`**

如果两个 Tensor 的维度数量不同，可以理解为：

> **在维度较少的 Tensor 前面补 `1`，然后再从后往前进行比较。**

如果所有对应维度都满足兼容条件，那么广播就可以成功发生。

最终输出 Tensor 的 shape，就是每个对应维度上**取较大的值**。

---

## 二、经典示例剖析

### 示例 1：二维矩阵加一维向量

假设我们有：

- `X` 的 shape：`[2, 3]`
- `b` 的 shape：`[3]`

代码如下：

```python
import torch

x = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])  # shape: [2, 3]

b = torch.tensor([10.0, 20.0, 30.0])  # shape: [3]

print(x + b)
```

### PyTorch 是如何进行 shape 对比的？

原始 shape：

```text
x: [2, 3]
b:    [3]
```

因为 `b` 少一个维度，所以可以理解为在前面补一个 `1`：

```text
x: [2, 3]
b: [1, 3]
```

然后从后往前比较。

#### 第 1 步：比较最后一维

```text
3 vs 3
```

两个维度长度相等，因此：

```text
兼容 ✓
```

#### 第 2 步：比较倒数第二维

```text
2 vs 1
```

其中一个维度为 `1`，因此：

```text
兼容 ✓
```

所以：

```python
x + b
```

可以成功执行。

---

### 广播过程中发生了什么？

可以**逻辑上**把 `b` 理解为从：

```python
[10.0, 20.0, 30.0]
```

扩展成：

```python
[
    [10.0, 20.0, 30.0],
    [10.0, 20.0, 30.0]
]
```

也就是：

```text
[1, 3] → [2, 3]
```

然后进行逐元素相加：

```text
[1, 2, 3] + [10, 20, 30] = [11, 22, 33]
[4, 5, 6] + [10, 20, 30] = [14, 25, 36]
```

最终结果：

```python
tensor([
    [11., 22., 33.],
    [14., 25., 36.]
])
```

输出 shape：

```text
[2, 3]
```

> 注意：这里的“扩展”主要是为了方便理解。PyTorch 的广播通常不会像 `repeat()` 那样真正复制出完整的数据。

---

## 三、更高维度的广播

在深度学习中，尤其是 Transformer、Attention、Batch 数据处理中，经常会遇到高维 Tensor 的广播。

例如：

```text
A.shape = [32, 128, 768]
B.shape = [1,   1, 768]
```

可以把它理解为：

```text
             Batch   Length   Dimension
A.shape =     32      128       768
B.shape =      1        1       768
```

从后往前比较。

### 第 1 个维度

```text
768 vs 768
```

相等：

```text
兼容 ✓
```

### 第 2 个维度

```text
128 vs 1
```

其中一个为 `1`：

```text
兼容 ✓
```

`B` 会在这一维逻辑上扩展：

```text
1 → 128
```

### 第 3 个维度

```text
32 vs 1
```

其中一个为 `1`：

```text
兼容 ✓
```

`B` 会在这一维逻辑上扩展：

```text
1 → 32
```

因此最终：

```text
A: [32, 128, 768]
B: [ 1,   1, 768]
        ↓ 广播
B: [32, 128, 768]
```

所以：

```python
A + B
```

可以成功执行。

最终输出 shape：

```text
[32, 128, 768]
```

---

## 四、什么时候广播会失败？

如果从后往前比较时，发现某个对应维度：

- 两个维度的长度**不相等**
- 并且两个维度**都不是 `1`**

那么广播就会失败。

PyTorch 通常会抛出类似下面的错误：

```text
RuntimeError: The size of tensor a must match the size of tensor b
at non-singleton dimension ...
```

---

### 错误示例

假设：

```text
A.shape = [2, 3]
B.shape = [2]
```

从后往前对齐：

```text
A: [2, 3]
B:    [2]
```

可以理解为：

```text
A: [2, 3]
B: [1, 2]
```

比较最后一维：

```text
3 vs 2
```

此时：

```text
3 != 2
```

并且：

```text
3 != 1
2 != 1
```

所以：

```text
不兼容 ✗
```

因此：

```python
A + B
```

会直接报错。

---

## 五、如何解决广播失败？

假设：

```python
A.shape == [2, 3]
B.shape == [2]
```

如果我们真正想表达的是：

> `B` 中的第一个元素加到 `A` 的第一行，第二个元素加到 `A` 的第二行。

那么应该把：

```text
B.shape = [2]
```

变成：

```text
B.shape = [2, 1]
```

可以使用：

```python
B = B.unsqueeze(1)
```

此时：

```text
A: [2, 3]
B: [2, 1]
```

从后往前比较：

```text
3 vs 1 → 兼容 ✓
2 vs 2 → 兼容 ✓
```

因此可以成功广播：

```text
B: [2, 1]
      ↓
   [2, 3]
```

例如：

```python
import torch

A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

B = torch.tensor([10, 20])

B = B.unsqueeze(1)

print(A.shape)
print(B.shape)

print(A + B)
```

输出：

```text
torch.Size([2, 3])
torch.Size([2, 1])
```

计算过程可以理解为：

```text
A:
1   2   3
4   5   6

B:
10
20

广播后：

10  10  10
20  20  20
```

最终：

```text
11  12  13
24  25  26
```

---

## 六、广播的 Shape 判断口诀

可以记住一句话：

> **从右往左对齐，维度相等或者有一个是 1，就可以广播。**

例如：

```text
[2, 3]
   [3]
```

补 `1`：

```text
[2, 3]
[1, 3]
```

可以广播：

```text
✓
```

---

再例如：

```text
[2, 3]
   [2]
```

补 `1`：

```text
[2, 3]
[1, 2]
```

最后一维：

```text
3 vs 2
```

不兼容：

```text
✗
```

---

再例如：

```text
[4, 3, 2]
[1, 3, 1]
```

从右往左：

```text
2 vs 1 → ✓
3 vs 3 → ✓
4 vs 1 → ✓
```

所以最终 shape：

```text
[4, 3, 2]
```

---

再例如：

```text
[5, 1, 4]
[   3, 4]
```

先补 `1`：

```text
[5, 1, 4]
[1, 3, 4]
```

从右往左：

```text
4 vs 4 → ✓
1 vs 3 → ✓
5 vs 1 → ✓
```

最终 shape：

```text
[5, 3, 4]
```

---

## 七、为什么要使用广播机制？

### 1. 代码更加简洁

如果没有广播，我们可能需要手动复制 Tensor：

```python
b = b.repeat(...)
```

而使用广播时，可以直接：

```python
x + b
```

PyTorch 自动帮我们处理 shape。

---

### 2. 节省内存

广播通常不会真的把 Tensor 的数据复制很多份。

例如：

```text
b.shape = [1, 1, 768]
```

广播到：

```text
[32, 128, 768]
```

可以在逻辑上理解成数据被扩展了，但通常不需要像 `repeat()` 那样真正创建这么多份数据。

因此可以显著减少内存和 GPU 显存的浪费。

---

### 3. 深度学习中非常常见

广播大量出现在：

- Bias 加法
- Batch 数据处理
- Transformer
- Attention
- Mask
- Normalization
- Loss 计算
- 特征缩放
- 矩阵与向量运算

例如神经网络中的：

```python
y = x @ W + b
```

其中：

```text
x @ W → [batch_size, output_dim]

b → [output_dim]
```

`b` 就会自动广播成：

```text
[batch_size, output_dim]
```

然后完成 Bias 加法。

---

## 八、广播机制总结

判断两个 Tensor 能否广播，只需要按照下面的流程：

```text
两个 Tensor
    ↓
Shape 从右往左对齐
    ↓
维度数量不同？
    ↓
少的前面补 1
    ↓
逐维比较
    ↓
相等？──────────→ 可以
    ↓ 否
其中一个是 1？──→ 可以
    ↓ 否
广播失败
```

核心规则只有一句：

> **从右往左比较，对应维度相等，或者其中一个为 `1`，就兼容。**

最终输出 shape：

> **每个对应维度取较大的那个值。**

例如：

```text
[5, 1, 4]
[1, 3, 4]
---------
[5, 3, 4]
```

最大值和 argmax

In [ ]:
import torch
x = torch.tensor([
    [1., 7., 3.],
    [9., 4., 6.]
])
values, indices = x.max(dim=1)
print(values)  # tensor([7., 9.])
print(indices)  # tensor([1, 0])  最大值的索引
print(x.argmax(dim=1))  # tensor([1, 0])  每一行的  最大值的索引

tensor([7., 9.])
tensor([1, 0])


tensor([1, 0])